version: '3.1'

services:
  db:
    ports:
      - 5432:5432
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mines
      POSTGRES_PASSWORD: mines
      POSTGRES_DB: mines

  sonar_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust


  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
#    environment:
#      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db:5432/postgres
#      - SONARQUBE_JDBC_USERNAME=postgres
#      - SONARQUBE_JDBC_PASSWORD=postgres
